import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { ExportData } from '../types'
import { CEREMONIES } from '../data/ceremonies'

const SPRINT_METRICS_KEY = 'sprint-metrics-sprints'
const SPRINT_METRICS_URL = 'https://agile-toolkit.github.io/sprint-metrics/'

interface SprintEntry {
  id: string
  name: string
  planned: number
  completed: number
  carriedOver: number
}

interface Props {
  data: ExportData
  onBack: () => void
}

function buildMarkdown(data: ExportData, t: (k: string, opts?: Record<string, unknown>) => string): string {
  const ceremony = CEREMONIES.find(c => c.type === data.ceremonyType)
  const name = ceremony ? t(ceremony.nameKey) : data.ceremonyType
  const lines: string[] = [
    `# ${name}`,
    `**Date:** ${data.date}`,
    `**Steps completed:** ${data.stepsCompleted} / ${data.totalSteps}`,
  ]

  if (data.participants && data.participants.length > 0) {
    lines.push('', '## Participants', ...data.participants.map(p => `- ${p}`))
  }

  if (data.retroNotes) {
    const { wellDone, toImprove, actions } = data.retroNotes
    if (wellDone.length > 0) {
      lines.push('', '## What went well', ...wellDone.map(n => `- ${n.text}`))
    }
    if (toImprove.length > 0) {
      lines.push('', '## To improve', ...toImprove.map(n => `- ${n.text}`))
    }
    if (actions.length > 0) {
      lines.push('', '## Actions', ...actions.map(n => `- [ ] ${n.text}`))
    }
  }

  lines.push('', `---`, `_Generated by Scrum Facilitator_`)
  return lines.join('\n')
}

export default function ExportView({ data, onBack }: Props) {
  const { t } = useTranslation()
  const [copied, setCopied] = useState(false)
  const [smExported, setSmExported] = useState(false)

  const markdown = buildMarkdown(data, t as (k: string, opts?: Record<string, unknown>) => string)

  const copy = async () => {
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const download = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `scrum-${data.ceremonyType}-${data.date.replace(/\//g, '-')}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportToSprintMetrics = () => {
    const existing: SprintEntry[] = (() => {
      try { return JSON.parse(localStorage.getItem(SPRINT_METRICS_KEY) ?? '[]') } catch { return [] }
    })()
    const entry: SprintEntry = {
      id: Date.now().toString(),
      name: data.date,
      planned: 0,
      completed: 0,
      carriedOver: 0,
    }
    localStorage.setItem(SPRINT_METRICS_KEY, JSON.stringify([...existing, entry]))
    window.open(SPRINT_METRICS_URL, '_blank', 'noopener,noreferrer')
    setSmExported(true)
    setTimeout(() => setSmExported(false), 4000)
  }

  return (
    <div className="flex flex-col gap-4 max-w-2xl">
      <div className="flex items-center gap-3 flex-wrap">
        <button onClick={onBack} className="btn-ghost">← {t('export.back')}</button>
        <h2 className="text-xl font-bold flex-1">{t('export.title')}</h2>
        {data.ceremonyType === 'review' && (
          <button onClick={exportToSprintMetrics} className="btn-secondary text-sm">
            📊 {t('export.sprintMetrics')}
          </button>
        )}
        <button onClick={download} className="btn-secondary text-sm">
          ⬇ {t('export.download')}
        </button>
        <button onClick={copy} className="btn-primary text-sm">
          {copied ? `✓ ${t('export.copied')}` : `📋 ${t('export.copy')}`}
        </button>
      </div>

      {smExported && (
        <div className="rounded-lg bg-green-50 border border-green-200 px-4 py-2 text-sm text-green-800">
          {t('export.sprintMetricsToast')}
        </div>
      )}

      <pre className="card p-4 text-xs text-gray-700 font-mono whitespace-pre-wrap overflow-x-auto leading-relaxed">
        {markdown}
      </pre>
    </div>
  )
}
