import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { ExportData, FeedbackItem } from '../types'
import { CEREMONIES, formatDuration } from '../data/ceremonies'
import { appendSprintEntryToSprintMetrics } from '../utils/sprintMetricsHandoff'
import { CheckIcon, ClipboardIcon, ArrowLeftIcon, ChartIcon, LinkIcon, DownloadIcon } from './icons'

const SPRINT_METRICS_URL = 'https://agile-toolkit.github.io/sprint-metrics/'
const IMPROVEMENT_BOARD_URL = 'https://agile-toolkit.github.io/improvement-board/'

interface Props {
  data: ExportData
  onBack: () => void
}

function buildMarkdown(data: ExportData, t: (k: string, opts?: Record<string, unknown>) => string): string {
  const ceremony = CEREMONIES.find(c => c.type === data.ceremonyType)
  const name = ceremony ? t(ceremony.nameKey) : data.ceremonyType
  const title = data.teamName ? `${name} — ${data.teamName}` : name
  const lines: string[] = [
    `# ${title}`,
  ]

  if (data.sprintGoal) {
    lines.push('', `> **Sprint Goal:** ${data.sprintGoal}`)
  }

  lines.push(
    '',
    `**Date:** ${data.date}`,
    `**Steps completed:** ${data.stepsCompleted} / ${data.totalSteps}`,
  )

  if (data.participants && data.participants.length > 0) {
    lines.push('', '## Participants', ...data.participants.map(p => `- ${p}`))
  }

  if (data.ceremonyType === 'daily' && data.impediments && data.impediments.length > 0) {
    lines.push('', '## Impediments', ...data.impediments.map(i => `- ${i}`))
  }

  if (data.ceremonyType === 'review' && data.feedbackItems && data.feedbackItems.length > 0) {
    const groups: { type: FeedbackItem['type']; heading: string }[] = [
      { type: 'question', heading: 'Questions' },
      { type: 'concern', heading: 'Concerns' },
      { type: 'praise', heading: 'Praise' },
    ]
    const rows = groups.flatMap(({ type, heading }) => {
      const forType = data.feedbackItems!.filter(f => f.type === type)
      if (forType.length === 0) return []
      return [
        '',
        `### ${heading}`,
        ...forType.map(f => `- ${f.from ? `[${f.from} — Stakeholder] ` : ''}${f.text}`),
      ]
    })
    if (rows.length > 0) {
      lines.push('', '## Stakeholder Feedback', ...rows)
    }
  }

  if (data.ceremonyType === 'review' && data.demoItems && data.demoItems.length > 0) {
    lines.push(
      '',
      '## Demo Checklist',
      ...data.demoItems.map(item =>
        item.demoed
          ? `- [x] ${item.text}${item.presenter ? ` — ${item.presenter}` : ''}`
          : `- [ ] ${item.text}${item.presenter ? ` — ${item.presenter}` : ''} (not shown)`,
      ),
    )
  }

  if (data.ceremonyType === 'retro' && data.retroNotes) {
    const actionNotes = Object.values(data.retroNotes).flat().filter(n => n.isAction)
    if (actionNotes.length > 0) {
      lines.push(
        '',
        '## ✅ Action Items',
        ...actionNotes.map(n => `- [ ] ${n.text}${n.owner ? ` — ${n.owner}` : ''}`),
      )
    }
  }

  if (data.stepTimings && data.stepTimings.length > 0 && ceremony) {
    const rows = ceremony.steps.flatMap(step => {
      const timing = data.stepTimings!.find(st => st.stepId === step.id)
      return timing ? [{ step, timing }] : []
    })
    if (rows.length > 0) {
      lines.push(
        '',
        '## Time Breakdown',
        '| Step | Planned | Actual | +/- |',
        '|------|---------|--------|-----|',
        ...rows.map(({ step, timing }) => {
          const delta = timing.actual - timing.planned
          const deltaStr = delta === 0 ? '0m' : `${delta > 0 ? '+' : '-'}${formatDuration(Math.abs(delta))}`
          return `| ${t(step.titleKey)} | ${formatDuration(timing.planned)} | ${formatDuration(timing.actual)} | ${deltaStr} |`
        }),
      )
    }
  }

  if (data.retroNotes) {
    for (const [key, notes] of Object.entries(data.retroNotes)) {
      if (notes.length > 0) {
        const heading = t(`retro.columns.${key}`, { defaultValue: key })
        lines.push('', `## ${heading}`, ...notes.map(n => `- ${n.text}`))
      }
    }
  }

  lines.push('', `---`, `_Generated by Scrum Facilitator_`)
  return lines.join('\n')
}

export default function ExportView({ data, onBack }: Props) {
  const { t } = useTranslation()
  const [copied, setCopied] = useState(false)
  const [smExported, setSmExported] = useState(false)

  const markdown = buildMarkdown(data, t as (k: string, opts?: Record<string, unknown>) => string)

  const copy = async () => {
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const download = () => {
    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `scrum-${data.ceremonyType}-${data.date.replace(/\//g, '-')}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportToSprintMetrics = () => {
    appendSprintEntryToSprintMetrics({
      id: Date.now().toString(),
      name: data.date,
      planned: 0,
      completed: 0,
      carriedOver: 0,
    })
    window.open(SPRINT_METRICS_URL, '_blank', 'noopener,noreferrer')
    setSmExported(true)
    setTimeout(() => setSmExported(false), 4000)
  }

  return (
    <div className="flex flex-col gap-4 max-w-2xl">
      <div className="flex items-center gap-3 flex-wrap">
        <button onClick={onBack} className="btn-ghost flex items-center gap-1"><ArrowLeftIcon className="w-3.5 h-3.5" /> {t('export.back')}</button>
        <h2 className="text-xl font-bold flex-1 dark:text-gray-50">{t('export.title')}</h2>
        {data.ceremonyType === 'review' && (
          <button onClick={exportToSprintMetrics} className="btn-secondary text-sm flex items-center gap-1.5">
            <ChartIcon className="w-4 h-4" /> {t('export.sprintMetrics')}
          </button>
        )}
        {data.ceremonyType === 'daily' && data.impediments && data.impediments.length > 0 && (
          <a
            href={IMPROVEMENT_BOARD_URL}
            target="_blank"
            rel="noopener noreferrer"
            className="btn-secondary text-sm flex items-center gap-1.5"
          >
            <LinkIcon className="w-4 h-4" /> {t('daily.openImprovementBoard')}
          </a>
        )}
        <button onClick={download} className="btn-secondary text-sm flex items-center gap-1.5">
          <DownloadIcon className="w-4 h-4" /> {t('export.download')}
        </button>
        <button onClick={copy} className="btn-primary text-sm inline-flex items-center gap-1.5">
          {copied ? <CheckIcon className="w-3.5 h-3.5" /> : <ClipboardIcon className="w-3.5 h-3.5" />}
          {copied ? t('export.copied') : t('export.copy')}
        </button>
      </div>

      {smExported && (
        <div className="rounded-lg bg-green-50 border border-green-200 px-4 py-2 text-sm text-green-800">
          {t('export.sprintMetricsToast')}
        </div>
      )}

      <pre className="card p-4 text-xs text-gray-700 dark:text-gray-300 font-mono whitespace-pre-wrap overflow-x-auto leading-relaxed">
        {markdown}
      </pre>
    </div>
  )
}
